### ISSUE TITLE
Bot is impersonal - Please add some personality

### ISSUE THREAD

**Issue by thedanfernandez** [BrianPeek/GitHubBot#4]
The bot right now is fine, but it really lacks a cool accent and personality. Can we build a framework to build personality-based bots like: 

- Mr. Belvedere from Mr. Belvedere
- Geoffrey from Fresh Prince of Bel Air
- Mrs. Garrett from Facts of Life
- Tony Macelli from Who's the Boss 
- VICI from Small Wonder
- Benson from Benson
- Charles from Charles in Charge

**Comment by BrianPeek** [comment]
Worst. Idea. Ever.

**Comment by BrianPeek** [comment]
Worst. Idea. Ever.

**Comment by BrianPeek** [comment]
Worst. Idea. Ever.
